"""empty message

Revision ID: 82372d11cf52
Revises: f547eaa3243f
Create Date: 2025-04-22 23:45:49.999328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82372d11cf52'
down_revision = 'f547eaa3243f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('may_create', sa.Boolean(), nullable=True),
    sa.Column('may_update', sa.Boolean(), nullable=True),
    sa.Column('may_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
